DELETE FROM "FENXT_DW"."BB"."DIM_PROJECTATTRIBUTE"
WHERE "ProjectAttributeDimID" IN(SELECT "ProjectAttributeDimID" From "FENXT_DW"."BB_DELTA"."DIM_PROJECTATTRIBUTE");

Insert Into "FENXT_DW"."BB"."DIM_PROJECTATTRIBUTE"
Select 
  PROJECTATTRIBUTEDIMID
, PROJECTATTRIBUTESYSTEMID
, PROJECTDIMID
, PROJECTSYSTEMID
, ATTRIBUTECATEGORY
, ATTRIBUTEDESCRIPTION
, COMMENTS
, ATTRIBUTEDATE
, SEQUENCE
, TYPEOFDATA
, REQUIRED
, MUSTBEUNIQUE
, IMPORTID
, DATEADDED
, DATECHANGED
From "FENXT_DW"."BB_DELTA"."DIM_PROJECTATTRIBUTE"
WHERE "UpdatedStatus" In('New','Modified');

