USE OSUADV_PROD.BI;

CREATE OR REPLACE TABLE "DNRCNCT_GradYear"
    (
        ProspectID varchar(20)
        ,degree varchar(100)
        ,gradyear INT
    )
 ;

INSERT INTO "DNRCNCT_GradYear"
SELECT
    C.CONSTITUENTID prospectid
    ,CONCAT(LEFT(E.DEGREE,CHARINDEX('-', E.DEGREE) - 2),'-',COALESCE(E.MAJOR,''), '-', COALESCE(E.SCHOOLTYPE,'')) AS degree
    ,E.GradYear AS gradyear
FROM 
    "OSUADV_PROD"."BI"."DNRCNCT_EDUCATION" E
        INNER JOIN "OSUADV_PROD"."RE"."CONSTITUENT" C ON C.CONSTITUENTSYSTEMID = E.CONSTITUENTSYSTEMID
        INNER JOIN"OSUADV_PROD"."BI"."DNRCNCT_InclLst_minus_ExclLst" IME ON C.CONSTITUENTSYSTEMID = IME.CONSTITUENTSYSTEMID
WHERE 
    E.DEGREE IS NOT NULL 
    AND E.DEGREE != 'ATD - ATTENDED/NO DEGREE'
ORDER BY
    C.CONSTITUENTID
    ,E.Seq

;