USE "OSUF_INTERFACES"."FACULTY_STAFF";

CREATE OR REPLACE TABLE "OSUF_INTERFACES"."FACULTY_STAFF"."SF_RelationshipObject" 
(
    External_System_ID NVARCHAR(255),
    Id NVARCHAR(18),
    IsDeleted NVARCHAR(18),
    LastReferencedDate NVARCHAR(50),
    LastViewedDate NVARCHAR(50),
    Name NVARCHAR(80),
    OSUF_Constituent_Role NVARCHAR(1300),
    OwnerId NVARCHAR(18),
    RE_Added_By NVARCHAR(80),
    RE_Date_Modified NVARCHAR(50),
    RE_Last_Changed_By NVARCHAR(80),
    RecordTypeId NVARCHAR(18),
    end_date NVARCHAR(50),
    start_date NVARCHAR(50),
    ucinn_ascendv2__Apply_Soft_Credit NVARCHAR(18),
    ucinn_ascendv2__Contact NVARCHAR(18),
    ucinn_ascendv2__Contact_Role_Formula NVARCHAR(1300),
    ucinn_ascendv2__Data_Source NVARCHAR(255),
    ucinn_ascendv2__End_Month NVARCHAR(255),
    ucinn_ascendv2__End_Year NVARCHAR(255),
    ucinn_ascendv2__Interim NVARCHAR(18),
    ucinn_ascendv2__Is_Guarantor NVARCHAR(18),
    ucinn_ascendv2__Notes STRING,
    ucinn_ascendv2__Prevent_Soft_Credit NVARCHAR(18),
    ucinn_ascendv2__Reciprocal_Relationship NVARCHAR(18),
    ucinn_ascendv2__Related_Constituent_Type_Formula NVARCHAR(1300),
    ucinn_ascendv2__Related_Contact NVARCHAR(18),
    ucinn_ascendv2__Related_Contact_Donor_ID_Formula NVARCHAR(1300),
    ucinn_ascendv2__Related_Contact_Name_Formula NVARCHAR(1300),
    ucinn_ascendv2__Related_Contact_Role NVARCHAR(255),
    ucinn_ascendv2__Relationship_Name_Auto_Number NVARCHAR(30),
    ucinn_ascendv2__Source NVARCHAR(255),
    ucinn_ascendv2__Start_Month NVARCHAR(255),
    ucinn_ascendv2__Start_Year NVARCHAR(255),
    ucinn_ascendv2__Status NVARCHAR(255)
)
