USE "OSUF_INTERFACES"."FACULTY_STAFF";

CREATE OR REPLACE TABLE "OSUF_INTERFACES"."FACULTY_STAFF"."SF_AddressObject"
(
    Custom_External_System_ID nvarchar(255),
    ER nvarchar(18),
    Id nvarchar(18),
    IsDeleted nvarchar(18),
    LastReferencedDate nvarchar(50),
    LastViewedDate nvarchar(50),
    Lost nvarchar(18),
    Name nvarchar(80),
    Needs_Research nvarchar(18),
    OwnerId nvarchar(18),
    ucinn_ascendv2__Address_Line_1 nvarchar(255),
    ucinn_ascendv2__Address_Line_2 nvarchar(255),
    ucinn_ascendv2__Address_Line_3 nvarchar(255),
    ucinn_ascendv2__Address_Line_4 nvarchar(255),
    ucinn_ascendv2__Address_Name_Auto_Number nvarchar(30),
    ucinn_ascendv2__Address_Verification_API_Request STRING,
    ucinn_ascendv2__Address_Verification_API_Response STRING,
    ucinn_ascendv2__City nvarchar(255),
    ucinn_ascendv2__Country nvarchar(255),
    ucinn_ascendv2__Country_ISO_Code nvarchar(255),
    ucinn_ascendv2__Country_Integration_Value nvarchar(255),
    ucinn_ascendv2__County nvarchar(255),
    ucinn_ascendv2__Data_Source nvarchar(255),
    ucinn_ascendv2__Do_Not_Override nvarchar(18),
    ucinn_ascendv2__External_System_ID nvarchar(255),
    ucinn_ascendv2__Is_Confirmed nvarchar(18),
    ucinn_ascendv2__Is_Verified nvarchar(18),
    ucinn_ascendv2__Location STRING,
    ucinn_ascendv2__Location__Latitude nvarchar(50),
    ucinn_ascendv2__Location__Longitude nvarchar(50),
    ucinn_ascendv2__Notes STRING,
    ucinn_ascendv2__Postal_Code nvarchar(25),
    ucinn_ascendv2__Presidential_Address_Line_1 nvarchar(255),
    ucinn_ascendv2__Presidential_Address_Line_2 nvarchar(255),
    ucinn_ascendv2__Presidential_Address_Line_3 nvarchar(255),
    ucinn_ascendv2__Presidential_Address_Line_4 nvarchar(255),
    ucinn_ascendv2__Presidential_City nvarchar(255),
    ucinn_ascendv2__Presidential_Country nvarchar(80),
    ucinn_ascendv2__Presidential_Postal_Code nvarchar(25),
    ucinn_ascendv2__Presidential_State nvarchar(100),
    ucinn_ascendv2__Presidential_Street_Formula nvarchar(1300),
    ucinn_ascendv2__Source nvarchar(255),
    ucinn_ascendv2__State nvarchar(255),
    ucinn_ascendv2__State_ISO_Code nvarchar(255),
    ucinn_ascendv2__State_Integration_Value nvarchar(255),
    ucinn_ascendv2__Street_Formula nvarchar(1300),
    ucinn_ascendv2__Verification_Response nvarchar(255),
    ucinn_ascendv2__Verification_Source nvarchar(255)
)
;