USE "OSUF_INTERFACES"."FACULTY_STAFF";

DROP TABLE "OSUF_INTERFACES"."FACULTY_STAFF"."SF_ContactObject";

DROP TABLE "OSUF_INTERFACES"."FACULTY_STAFF"."SF_RelationshipObject";

DROP TABLE "OSUF_INTERFACES"."FACULTY_STAFF"."SF_PhoneObject";

DROP TABLE "OSUF_INTERFACES"."FACULTY_STAFF"."SF_EmailObject";

DROP TABLE "OSUF_INTERFACES"."FACULTY_STAFF"."SF_AddressObject";

DROP TABLE "OSUF_INTERFACES"."FACULTY_STAFF"."SF_AddressRelationObject";