USE OSUADV_PROD.BI;

SELECT DISTINCT
    C.CONSTITUENTID ProspectID
    ,CASE 
        WHEN gi.InstallmentStatus = 'Write-off' AND CGPRAMOUNT = 0 THEN InstallmentAmount 
        ELSE CGPRAMOUNT 
        END AS GiftAmount
    --,CGPRAMOUNT    
    ,GIFTDATE
    ,CASE 
        WHEN FC.FUNDID IS NULL THEN CONCAT('DO NOT SOLICIT- ',CPR.FUNDDESCRIPTION) 
        WHEN gi.InstallmentStatus = 'Write-off' AND CGPRAMOUNT = 0 THEN CONCAT('Write-Off- ',CPR.FUNDDESCRIPTION)
        ELSE CONCAT(FC.FUNDDESCRIPTION, '(',FC.FUNDID,')') 
        END AS designation
    --,CONCAT(FC.FUNDDESCRIPTION, '(',FC.FUNDID,')')
    ,CASE WHEN CPR.ISNETCOMMUNITYGIFT = 'Yes' THEN 'Y' ELSE 'N' END paidwithcreditcardYN
    ,'' source
 

FROM 
    "OSUADV_PROD"."BI"."OSUF_COMPREHENSIVE_PRODUCTION_AND_RECEIPTS" CPR
    INNER JOIN "OSUADV_PROD"."RE"."CONSTITUENT" C ON C.CONSTITUENTSYSTEMID = CPR.CONSTITUENTSYSTEMID
    INNER JOIN "OSUADV_PROD"."BI"."DNRCNCT_Household" h ON h.PRIMARYPROSPECTID = c.CONSTITUENTID
    LEFT OUTER JOIN (
                      SELECT
                        FUNDID
                        ,FUNDDESCRIPTION
                        ,FA.ATTRIBUTEDESCRIPTION COLLEGE

                      FROM 
                        "OSUADV_PROD"."RE"."FUND" F
                        INNER JOIN "OSUADV_PROD"."RE"."OSUF_ISAG_SOLICITABLEFUND" SF ON SF.FUNDSYSTEMID = F.FUNDSYSTEMID AND ISAG_SOLICITABLEFUND = 'Yes'
                        LEFT OUTER JOIN "OSUADV_PROD"."RE"."FUND_DTL_ATTRIBUTES" FA ON FA.FUNDSYSTEMID = F.FUNDSYSTEMID AND ATTRIBUTECATEGORY = 'College'
                ) FC ON FC.FUNDID = CPR.FUNDID
                
     LEFT OUTER JOIN "OSUADV_PROD"."RE"."GIFT_DTL_INSTALLMENTS" gi ON CPR.GiftSystemID = gi.GiftSystemID
     
 WHERE
    CPR.DATASOURCE = 'Development'
AND CPR.MEASURE = 'Production'