USE OSUADV_PROD.BI;

CREATE OR REPLACE TABLE "DNRCNCT_Gifts"
    (
        prospectID varchar(20)
        ,GiftAmount decimal(20,2)
        ,GiftDate date
        ,Designation varchar(1000)
        ,PaidWithCreditCardYN varchar(5)
        ,source varchar(50)
    )
 ;

INSERT INTO "DNRCNCT_Gifts"
SELECT
  C.CONSTITUENTID ProspectID
  ,CGPRAMOUNT GiftAmount
  ,GIFTDATE
  ,CASE WHEN FC.FUNDID IS NULL THEN CONCAT('DO NOT SOLICIT- ',CPR.FUNDDESCRIPTION) ELSE CONCAT(FC.FUNDDESCRIPTION, '(',FC.FUNDID,')') END designation
  ,CASE WHEN CPR.ISNETCOMMUNITYGIFT = 'Yes' THEN 'Y' ELSE 'N' END paidwithcreditcardYN
  ,'' source

FROM 
    "OSUADV_PROD"."BI"."OSUF_COMPREHENSIVE_PRODUCTION_AND_RECEIPTS" CPR
    INNER JOIN "OSUADV_PROD"."RE"."CONSTITUENT" C ON C.CONSTITUENTSYSTEMID = CPR.CONSTITUENTSYSTEMID
    INNER JOIN "OSUADV_PROD"."BI"."DNRCNCT_InclLst_minus_ExclLst" IME ON IME.CONSTITUENTSYSTEMID = CPR.CONSTITUENTSYSTEMID
    LEFT OUTER JOIN (
                      SELECT
                        FUNDID
                        ,FUNDDESCRIPTION
                        ,FA.ATTRIBUTEDESCRIPTION COLLEGE

                      FROM 
                        "OSUADV_PROD"."RE"."FUND" F
                        INNER JOIN "OSUADV_PROD"."RE"."OSUF_ISAG_SOLICITABLEFUND" SF ON SF.FUNDSYSTEMID = F.FUNDSYSTEMID AND ISAG_SOLICITABLEFUND = 'Yes'
                        LEFT OUTER JOIN "OSUADV_PROD"."RE"."FUND_DTL_ATTRIBUTES" FA ON FA.FUNDSYSTEMID = F.FUNDSYSTEMID AND ATTRIBUTECATEGORY = 'College'
                ) FC ON FC.FUNDID = CPR.FUNDID