USE OSUADV_PROD.BI;

/*============================================================================================
--
--Description: ConstituentCodes for HouseHolding
--             This is used for determining who is the PrimaryID for the calling data
--
============================================================================================*/

CREATE OR REPLACE TEMPORARY TABLE tmp_ConCodesforHouseholding
										  (
											   CONSTITUENTSYSTEMID INT          NOT NULL
											 , CONSTITUENTCODE  VARCHAR(100)
										  );

INSERT INTO tmp_ConCodesforHouseholding 

SELECT DISTINCT
  IL.CONSTITUENTSYSTEMID

, CASE 
		WHEN PCC.CONSTITUENTCODE IN ('Alumni', 'Attended', 'Student', 'Student Unenrolled') THEN PCC.CONSTITUENTCODE
		WHEN PCC.CONSTITUENTCODE = 'Friend' AND GivingHistory.CONSTITUENTSYSTEMID IS NULL AND Parent.CONSTITUENTSYSTEMID IS NOT NULL THEN Parent.CONSTITUENTCODE
		ELSE PCC.CONSTITUENTCODE
  END AS CONSTITUENTCODE

FROM
 "OSUADV_PROD"."BI"."DNRCNCT_InclLst_minus_ExclLst" AS IL
							
							INNER JOIN 
											(
												SELECT
													CONSTITUENTSYSTEMID
													, CONSTITUENTCODE
												
												FROM
													"OSUADV_PROD"."RE"."OSUF_PRIMARYCONSTITUENTCODE"
																										
											) AS PCC ON IL.CONSTITUENTSYSTEMID = PCC.CONSTITUENTSYSTEMID

							LEFT OUTER JOIN
											(

												SELECT	
													CONSTITUENTSYSTEMID
													, CONSTITUENTCODE

												FROM																		
													"OSUADV_PROD"."RE"."CONSTITUENT_DTL_CONSTITUENTCODES"

												WHERE 
													CONSTITUENTCODE = 'Parent'
													
											) AS Parent ON IL.CONSTITUENTSYSTEMID = Parent.CONSTITUENTSYSTEMID

							LEFT OUTER JOIN
											(
												SELECT
												  CONSTITUENTSYSTEMID

												FROM 
													"OSUADV_PROD"."RE"."CONSTITUENT_DTL_FINANCIALINFORMATION"

												WHERE 
													INFORMATIONTYPE = 'Lifetime Comprehensive Giving'
												AND INFORMATIONSOURCE = 'OSU Foundation'
												AND VALUE > 0

											) AS GivingHistory ON IL.CONSTITUENTSYSTEMID = GivingHistory.CONSTITUENTSYSTEMID




ORDER BY 
  IL.CONSTITUENTSYSTEMID
;



/*============================================================================================
--
--Primary ID to Consider which ID is listed first from the left
--
============================================================================================*/
CREATE OR REPLACE TEMPORARY TABLE tmp_PRIMARYID

										  (
											   CONSTITUENTSYSTEMID INT          NOT NULL
										  );

INSERT INTO tmp_PRIMARYID 


SELECT 
  Q.CONSTITUENTSYSTEMID

FROM
	(
		--Married and both spouses have a constituent record
		SELECT DISTINCT
		  CASE 

				WHEN SeedList.CONSTITUENTSYSTEMID   IS NOT NULL AND SPSeedList.CONSTITUENTSYSTEMID IS NULL THEN C.CONSTITUENTSYSTEMID
				WHEN SPSeedList.CONSTITUENTSYSTEMID IS NOT NULL AND SeedList.CONSTITUENTSYSTEMID   IS NULL THEN SPC.CONSTITUENTSYSTEMID
				WHEN SeedList.CONSTITUENTSYSTEMID   IS NOT NULL AND SPSeedList.CONSTITUENTSYSTEMID IS NOT NULL AND C.CONSTITUENTSYSTEMID =  C.HOUSEHOLDSYSTEMID  THEN C.CONSTITUENTSYSTEMID
				WHEN SeedList.CONSTITUENTSYSTEMID   IS NOT NULL AND SPSeedList.CONSTITUENTSYSTEMID IS NOT NULL AND C.CONSTITUENTSYSTEMID <> C.HOUSEHOLDSYSTEMID  THEN SPC.CONSTITUENTSYSTEMID
				
				WHEN PCC.CONSTITUENTCODE   = 'Alumni' AND SPPCC.CONSTITUENTCODE <> 'Alumni' THEN C.CONSTITUENTSYSTEMID
				WHEN SPPCC.CONSTITUENTCODE = 'Alumni' AND PCC.CONSTITUENTCODE   <> 'Alumni' THEN SPC.CONSTITUENTSYSTEMID
				WHEN PCC.CONSTITUENTCODE   = 'Alumni' AND SPPCC.CONSTITUENTCODE =  'Alumni' AND COALESCE(HardCreditGiftCount.GiftCount, 0)   > COALESCE(SPHardCreditGiftCount.GiftCount, 0) THEN C.CONSTITUENTSYSTEMID
				WHEN PCC.CONSTITUENTCODE   = 'Alumni' AND SPPCC.CONSTITUENTCODE =  'Alumni' AND COALESCE(SPHardCreditGiftCount.GiftCount, 0) > COALESCE(HardCreditGiftCount.GiftCount, 0)   THEN SPC.CONSTITUENTSYSTEMID
				WHEN PCC.CONSTITUENTCODE   = 'Alumni' AND SPPCC.CONSTITUENTCODE =  'Alumni' AND COALESCE(SPHardCreditGiftCount.GiftCount, 0) = COALESCE(HardCreditGiftCount.GiftCount, 0) AND C.CONSTITUENTSYSTEMID =  C.HOUSEHOLDSYSTEMID  THEN C.CONSTITUENTSYSTEMID
				WHEN PCC.CONSTITUENTCODE   = 'Alumni' AND SPPCC.CONSTITUENTCODE =  'Alumni' AND COALESCE(SPHardCreditGiftCount.GiftCount, 0) = COALESCE(HardCreditGiftCount.GiftCount, 0) AND C.CONSTITUENTSYSTEMID <> C.HOUSEHOLDSYSTEMID  THEN SPC.CONSTITUENTSYSTEMID


				WHEN PCC.CONSTITUENTCODE   = 'Attended' AND SPPCC.CONSTITUENTCODE <> 'Attended' THEN C.CONSTITUENTSYSTEMID
				WHEN SPPCC.CONSTITUENTCODE = 'Attended' AND PCC.CONSTITUENTCODE   <> 'Attended' THEN SPC.CONSTITUENTSYSTEMID
				WHEN PCC.CONSTITUENTCODE   = 'Attended' AND SPPCC.CONSTITUENTCODE =  'Attended' AND COALESCE(HardCreditGiftCount.GiftCount, 0)   > COALESCE(SPHardCreditGiftCount.GiftCount, 0) THEN C.CONSTITUENTSYSTEMID
				WHEN PCC.CONSTITUENTCODE   = 'Attended' AND SPPCC.CONSTITUENTCODE =  'Attended' AND COALESCE(SPHardCreditGiftCount.GiftCount, 0) > COALESCE(HardCreditGiftCount.GiftCount, 0)   THEN SPC.CONSTITUENTSYSTEMID
				WHEN PCC.CONSTITUENTCODE   = 'Attended' AND SPPCC.CONSTITUENTCODE =  'Attended' AND COALESCE(SPHardCreditGiftCount.GiftCount, 0) = COALESCE(HardCreditGiftCount.GiftCount, 0) AND C.CONSTITUENTSYSTEMID =  C.HOUSEHOLDSYSTEMID  THEN C.CONSTITUENTSYSTEMID
				WHEN PCC.CONSTITUENTCODE   = 'Attended' AND SPPCC.CONSTITUENTCODE =  'Attended' AND COALESCE(SPHardCreditGiftCount.GiftCount, 0) = COALESCE(HardCreditGiftCount.GiftCount, 0) AND C.CONSTITUENTSYSTEMID <> C.HOUSEHOLDSYSTEMID  THEN SPC.CONSTITUENTSYSTEMID

				WHEN PCC.CONSTITUENTCODE   = 'McKnight Center for the Performing Arts' AND SPPCC.CONSTITUENTCODE <> 'Attended' THEN C.CONSTITUENTSYSTEMID
				WHEN SPPCC.CONSTITUENTCODE = 'McKnight Center for the Performing Arts' AND PCC.CONSTITUENTCODE   <> 'Attended' THEN SPC.CONSTITUENTSYSTEMID
				WHEN PCC.CONSTITUENTCODE   = 'McKnight Center for the Performing Arts' AND SPPCC.CONSTITUENTCODE =  'Attended' AND COALESCE(HardCreditGiftCount.GiftCount, 0)   > COALESCE(SPHardCreditGiftCount.GiftCount, 0) THEN C.CONSTITUENTSYSTEMID
				WHEN PCC.CONSTITUENTCODE   = 'McKnight Center for the Performing Arts' AND SPPCC.CONSTITUENTCODE =  'Attended' AND COALESCE(SPHardCreditGiftCount.GiftCount, 0) > COALESCE(HardCreditGiftCount.GiftCount, 0)   THEN SPC.CONSTITUENTSYSTEMID
				WHEN PCC.CONSTITUENTCODE   = 'McKnight Center for the Performing Arts' AND SPPCC.CONSTITUENTCODE =  'Attended' AND COALESCE(SPHardCreditGiftCount.GiftCount, 0) = COALESCE(HardCreditGiftCount.GiftCount, 0) AND C.CONSTITUENTSYSTEMID =  C.HOUSEHOLDSYSTEMID  THEN C.CONSTITUENTSYSTEMID
				WHEN PCC.CONSTITUENTCODE   = 'McKnight Center for the Performing Arts' AND SPPCC.CONSTITUENTCODE =  'Attended' AND COALESCE(SPHardCreditGiftCount.GiftCount, 0) = COALESCE(HardCreditGiftCount.GiftCount, 0) AND C.CONSTITUENTSYSTEMID <> C.HOUSEHOLDSYSTEMID  THEN SPC.CONSTITUENTSYSTEMID

				WHEN PCC.CONSTITUENTCODE   = 'KOSU Donor' AND SPPCC.CONSTITUENTCODE <> 'KOSU Donor' THEN C.CONSTITUENTSYSTEMID
				WHEN SPPCC.CONSTITUENTCODE = 'KOSU Donor' AND PCC.CONSTITUENTCODE   <> 'KOSU Donor' THEN SPC.CONSTITUENTSYSTEMID
				WHEN PCC.CONSTITUENTCODE   = 'KOSU Donor' AND SPPCC.CONSTITUENTCODE =  'KOSU Donor' AND COALESCE(HardCreditGiftCount.GiftCount, 0)   > COALESCE(SPHardCreditGiftCount.GiftCount, 0) THEN C.CONSTITUENTSYSTEMID
				WHEN PCC.CONSTITUENTCODE   = 'KOSU Donor' AND SPPCC.CONSTITUENTCODE =  'KOSU Donor' AND COALESCE(SPHardCreditGiftCount.GiftCount, 0) > COALESCE(HardCreditGiftCount.GiftCount, 0)   THEN SPC.CONSTITUENTSYSTEMID
				WHEN PCC.CONSTITUENTCODE   = 'KOSU Donor' AND SPPCC.CONSTITUENTCODE =  'KOSU Donor' AND COALESCE(SPHardCreditGiftCount.GiftCount, 0) = COALESCE(HardCreditGiftCount.GiftCount, 0) AND C.CONSTITUENTSYSTEMID =  C.HOUSEHOLDSYSTEMID  THEN C.CONSTITUENTSYSTEMID
				WHEN PCC.CONSTITUENTCODE   = 'KOSU Donor' AND SPPCC.CONSTITUENTCODE =  'KOSU Donor' AND COALESCE(SPHardCreditGiftCount.GiftCount, 0) = COALESCE(HardCreditGiftCount.GiftCount, 0) AND C.CONSTITUENTSYSTEMID <> C.HOUSEHOLDSYSTEMID  THEN SPC.CONSTITUENTSYSTEMID

				WHEN PCC.CONSTITUENTCODE   = 'Friend' AND SPPCC.CONSTITUENTCODE <> 'Friend' THEN C.CONSTITUENTSYSTEMID
				WHEN SPPCC.CONSTITUENTCODE = 'Friend' AND PCC.CONSTITUENTCODE   <> 'Friend' THEN SPC.CONSTITUENTSYSTEMID
				WHEN PCC.CONSTITUENTCODE   = 'Friend' AND SPPCC.CONSTITUENTCODE =  'Friend' AND COALESCE(HardCreditGiftCount.GiftCount, 0)   > COALESCE(SPHardCreditGiftCount.GiftCount, 0) THEN C.CONSTITUENTSYSTEMID
				WHEN PCC.CONSTITUENTCODE   = 'Friend' AND SPPCC.CONSTITUENTCODE =  'Friend' AND COALESCE(SPHardCreditGiftCount.GiftCount, 0) > COALESCE(HardCreditGiftCount.GiftCount, 0)   THEN SPC.CONSTITUENTSYSTEMID
				WHEN PCC.CONSTITUENTCODE   = 'Friend' AND SPPCC.CONSTITUENTCODE =  'Friend' AND COALESCE(SPHardCreditGiftCount.GiftCount, 0) = COALESCE(HardCreditGiftCount.GiftCount, 0) AND C.CONSTITUENTSYSTEMID =  C.HOUSEHOLDSYSTEMID  THEN C.CONSTITUENTSYSTEMID
				WHEN PCC.CONSTITUENTCODE   = 'Friend' AND SPPCC.CONSTITUENTCODE =  'Friend' AND COALESCE(SPHardCreditGiftCount.GiftCount, 0) = COALESCE(HardCreditGiftCount.GiftCount, 0) AND C.CONSTITUENTSYSTEMID <> C.HOUSEHOLDSYSTEMID  THEN SPC.CONSTITUENTSYSTEMID


				WHEN PCC.CONSTITUENTCODE   = 'Parent' AND SPPCC.CONSTITUENTCODE <> 'Parent' THEN C.CONSTITUENTSYSTEMID
				WHEN SPPCC.CONSTITUENTCODE = 'Parent' AND PCC.CONSTITUENTCODE   <> 'Parent' THEN SPC.CONSTITUENTSYSTEMID
				WHEN PCC.CONSTITUENTCODE   = 'Parent' AND SPPCC.CONSTITUENTCODE =  'Parent' AND COALESCE(HardCreditGiftCount.GiftCount, 0)   > COALESCE(SPHardCreditGiftCount.GiftCount, 0) THEN C.CONSTITUENTSYSTEMID
				WHEN PCC.CONSTITUENTCODE   = 'Parent' AND SPPCC.CONSTITUENTCODE =  'Parent' AND COALESCE(SPHardCreditGiftCount.GiftCount, 0) > COALESCE(HardCreditGiftCount.GiftCount, 0)   THEN SPC.CONSTITUENTSYSTEMID
				WHEN PCC.CONSTITUENTCODE   = 'Parent' AND SPPCC.CONSTITUENTCODE =  'Parent' AND COALESCE(SPHardCreditGiftCount.GiftCount, 0) = COALESCE(HardCreditGiftCount.GiftCount, 0) AND C.CONSTITUENTSYSTEMID =  C.HOUSEHOLDSYSTEMID  THEN C.CONSTITUENTSYSTEMID
				WHEN PCC.CONSTITUENTCODE   = 'Parent' AND SPPCC.CONSTITUENTCODE =  'Parent' AND COALESCE(SPHardCreditGiftCount.GiftCount, 0) = COALESCE(HardCreditGiftCount.GiftCount, 0) AND C.CONSTITUENTSYSTEMID <> C.HOUSEHOLDSYSTEMID  THEN SPC.CONSTITUENTSYSTEMID


				--These are constituents who have con codes that we are not considering, so just using HOH
				WHEN C.CONSTITUENTSYSTEMID =  C.HOUSEHOLDSYSTEMID  THEN C.CONSTITUENTSYSTEMID
				WHEN C.CONSTITUENTSYSTEMID <> C.HOUSEHOLDSYSTEMID  THEN SPC.CONSTITUENTSYSTEMID
		  END AS CONSTITUENTSYSTEMID

		FROM
		  "OSUADV_PROD"."RE"."CONSTITUENT" AS C
									INNER JOIN tmp_ConCodesforHouseholding AS PCC ON C.CONSTITUENTSYSTEMID = PCC.CONSTITUENTSYSTEMID
							
									INNER JOIN "OSUADV_PROD"."RE"."CONSTITUENT" AS SPC ON C.SPOUSECONSTITUENTSYSTEMID = SPC.CONSTITUENTSYSTEMID
									LEFT OUTER JOIN tmp_ConCodesforHouseholding AS SPPCC ON SPC.CONSTITUENTSYSTEMID = SPPCC.CONSTITUENTSYSTEMID
							
									
									LEFT OUTER JOIN "OSUADV_PROD"."BI"."DNRCNCT_SeedList" AS SeedList ON C.CONSTITUENTSYSTEMID = SeedList.CONSTITUENTSYSTEMID
									LEFT OUTER JOIN "OSUADV_PROD"."BI"."DNRCNCT_SeedList" AS SPSeedList ON SPC.CONSTITUENTSYSTEMID = SPSeedList.CONSTITUENTSYSTEMID



									LEFT OUTER JOIN
													(
														SELECT 
														  CONSTITUENTSYSTEMID
														, COUNT(1) AS GiftCount

														FROM
														  "OSUADV_PROD"."RE"."GIFT"

														GROUP BY 
														  CONSTITUENTSYSTEMID
													) AS HardCreditGiftCount ON C.CONSTITUENTSYSTEMID = HardCreditGiftCount.CONSTITUENTSYSTEMID


									LEFT OUTER JOIN
													(
														SELECT 
														  CONSTITUENTSYSTEMID
														, COUNT(1) AS GiftCount

														FROM
														  "OSUADV_PROD"."RE"."GIFT"

														GROUP BY 
														  CONSTITUENTSYSTEMID
													) AS SPHardCreditGiftCount ON SPC.CONSTITUENTSYSTEMID = SPHardCreditGiftCount.CONSTITUENTSYSTEMID

		WHERE
			SPC.CONSTITUENTID IS NOT NULL


		UNION
		--Single or Married but one spouse has a constituent record
		SELECT
		  C.CONSTITUENTSYSTEMID


		FROM
		  "OSUADV_PROD"."RE"."CONSTITUENT" AS C
									INNER JOIN "OSUADV_PROD"."BI"."DNRCNCT_InclLst_minus_ExclLst" AS IL ON C.CONSTITUENTSYSTEMID = IL.CONSTITUENTSYSTEMID
									LEFT OUTER JOIN "OSUADV_PROD"."RE"."CONSTITUENT" AS SPC ON C.SPOUSECONSTITUENTSYSTEMID = SPC.CONSTITUENTSYSTEMID

		WHERE
			SPC.CONSTITUENTID IS NULL
	) AS Q

ORDER BY 
  Q.CONSTITUENTSYSTEMID
;



/*============================================================================================
--
--Household data import file
--
============================================================================================*/
CREATE OR REPLACE TABLE "DNRCNCT_Household"
						(
						       primaryprospectid    VARCHAR(20) NOT NULL 
                             , relatedpropsectid    VARCHAR(20)
                             , relationship         VARCHAR(1)
						);

INSERT INTO "DNRCNCT_Household"

SELECT
      H.primaryprospectid                   AS primaryprospectid
    , COALESCE(H.relatedpropsectid , '')    AS relatedpropsectid
    , COALESCE(H.relationship, '')          AS relationship
    
FROM 
    (
        SELECT DISTINCT
              C.CONSTITUENTID AS primaryprospectid
            , SPC.CONSTITUENTID AS relatedpropsectid
            , CASE WHEN SPC.CONSTITUENTID IS NOT NULL THEN 'S' ELSE '' END AS relationship

        FROM 
             tmp_PRIMARYID AS PrimaryID     INNER JOIN "OSUADV_PROD"."RE"."CONSTITUENT" AS C ON PrimaryID.CONSTITUENTSYSTEMID = C.CONSTITUENTSYSTEMID
                                            LEFT OUTER JOIN "OSUADV_PROD"."RE"."CONSTITUENT" AS SPC ON C.SPOUSECONSTITUENTSYSTEMID = SPC.CONSTITUENTSYSTEMID
      
     ) H
;     