USE OSUADV_PROD.BI;

CREATE OR REPLACE TABLE "DNRCNCT_Manager"
    (
        prospectID varchar(20)
        ,value varchar(1000)
    )
 ;

INSERT INTO "DNRCNCT_Manager"
SELECT
  CONSTITUENTID prospectID
  ,LISTAGG(MANAGERNAME, ', ') WITHIN GROUP(ORDER BY SOLICITORTYPE) value

FROM 
    (
      SELECT 
        C.CONSTITUENTID
        ,C.CONSTITUENTSYSTEMID
        ,RAS.SOLICITORTYPE
        ,CASE WHEN SC.CONSTITUENTID = '344954' THEN 'Lauren Kidd' ELSE SC.FULLNAME END AS MANAGERNAME
        ,SC.CONSTITUENTID MANAGERCONSTITUENTID
        ,CASE 
            WHEN SC.FULLNAME = 'Leadership Gift Manager' THEN 1 
            ELSE 2 
        END AS RANK
      FROM 
        "OSUADV_PROD"."RE"."REL_ASSIGNEDSOLICITORS" RAS
        INNER JOIN "OSUADV_PROD"."RE"."CONSTITUENT" C ON C.CONSTITUENTSYSTEMID = RAS.CONSTITUENTSYSTEMID
        LEFT OUTER JOIN "OSUADV_PROD"."RE"."CONSTITUENT" SC ON SC.CONSTITUENTSYSTEMID = RAS.SOLICITORCONSTITUENTSYSTEMID

      WHERE 
        SOLICITORTYPE IN ('Manager 1', 'Manager 2', 'Manager 3', 'Manager 4')
    ) MGR
    INNER JOIN "OSUADV_PROD"."BI"."DNRCNCT_InclLst_minus_ExclLst" IME ON IME.CONSTITUENTSYSTEMID = MGR.CONSTITUENTSYSTEMID

GROUP BY CONSTITUENTID
